# Use the Nginx image from Docker Hub
FROM nginx:alpine

# Copy the static files into Nginx's public directory
COPY dkroell/ /usr/share/nginx/html/dkroell
COPY public/* /usr/share/nginx/html/dkroell/
RUN mkdir -p /usr/share/nginx/html/dkroell/.well-known/acme-challenge

# Optional: if you have a custom Nginx configuration, you can use it:
COPY nginx.conf /etc/nginx/nginx.conf
