# Build stage
FROM node:alpine AS builder

WORKDIR /app

ADD package.json /app/package.json
ADD dkroell/ /app/dkroell
ADD public/ /app/public
ADD app.js /app/app.js

RUN npm install

# Runtime stage
FROM node:alpine

WORKDIR /app

COPY --from=builder /app /app/

RUN npm install --production

CMD ["npm", "start", "--port=8481"]